blank_issues_enabled: false
contact_links:
  - name: 💬 Pertanyaan / Diskusi
    url: https://web.facebook.com/myruldev
    about: Untuk tanya jawab umum, hubungi lewat Facebook myrul.dev
  - name: 🌐 Website
    url: https://www.myrul.dev
    about: Info lebih lanjut tentang proyek & penulis
